---
# Crossplane EnvironmentConfig for DNS Configuration
# https://docs.crossplane.io/latest/concepts/environment-configs/
apiVersion: apiextensions.crossplane.io/v1beta1
kind: EnvironmentConfig
metadata:
  name: dns-config
  annotations:
    crossplane.io/version: "v2.0"
    description: "DNS zone configuration for the platform"
data:
  # DNS zone for all DNS records
  zone: portal.example.com
  
  # Additional configuration that could be used
  # nameservers:
  #   - ns1.example.com
  #   - ns2.example.com
  # contact: admin@example.com