---
# GitHub Actions workflow to build and publish Crossplane Configuration packages
name: Release Configuration Package

on:
  # Trigger on version tags
  push:
    tags:
      - 'v*.*.*'  # Semantic version tags (e.g., v1.0.0, v2.1.3)
  
  # Allow manual trigger for testing
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag to use (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'

env:
  # Use GitHub Container Registry (ghcr.io) for the Open Service Portal organization
  REGISTRY: ghcr.io
  PACKAGE_NAME: open-service-portal/configuration-dns-record

jobs:
  build-and-push:
    name: Build and Push Configuration Package
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
      id-token: write  # For signing with cosign
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Fetch all history for all tags and branches
          fetch-depth: 0
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          # Enable multi-platform builds
          platforms: linux/amd64,linux/arm64
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Install Crossplane CLI
        run: |
          # Install latest Crossplane CLI
          curl -sL https://raw.githubusercontent.com/crossplane/crossplane/master/install.sh | sh
          sudo mv crossplane /usr/local/bin/
          # Ignore missing Crossplane server
          crossplane version 2>/dev/null || true
      
      - name: Determine version
        id: version
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            VERSION="${{ github.event.inputs.version }}"
          else
            VERSION="${{ github.ref_name }}"
          fi
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT
          echo "Building version: ${VERSION}"

      - name: Build Configuration package
        run: |
          # Add version to package metadata
          yq -i '.metadata.annotations."openportal.dev/version" = env(VERSION)' configuration/crossplane.yaml

          # Build the .xpkg file
          crossplane xpkg build \
            --package-root=configuration/ \
            --package-file=configuration-dns-record.xpkg
        env:
          VERSION: ${{ steps.version.outputs.VERSION }}
      
      - name: Push package to registry
        run: |
          VERSION="${{ steps.version.outputs.VERSION }}"
          
          # Push with version tag
          crossplane xpkg push \
            --package-files=configuration-dns-record.xpkg \
            ${{ env.REGISTRY }}/${{ env.PACKAGE_NAME }}:${VERSION}
          
          # Also push as 'latest' if this is not a pre-release
          if [[ ! "${VERSION}" =~ -(alpha|beta|rc) ]]; then
            crossplane xpkg push \
              --package-files=configuration-dns-record.xpkg \
              ${{ env.REGISTRY }}/${{ env.PACKAGE_NAME }}:latest
          fi
      
      - name: Generate package manifest for catalog
        run: |
          VERSION="${{ steps.version.outputs.VERSION }}"
          
          # Create a catalog entry file
          cat > catalog-entry.yaml <<EOF
          ---
          # DNS Record Configuration Package
          # Provides XRD and Composition for DNS record management
          apiVersion: pkg.crossplane.io/v1
          kind: Configuration
          metadata:
            name: configuration-dns-record
            namespace: crossplane-system
          spec:
            package: ${{ env.REGISTRY }}/${{ env.PACKAGE_NAME }}:${VERSION}

            # Package pull policy
            # IfNotPresent: Only download if not in cache (recommended for production)
            # Always: Check for updates on reconciliation (useful for development)
            packagePullPolicy: IfNotPresent

            # Revision activation policy
            # Automatic: New revisions become active immediately (good for single-tenant)
            # Manual: Requires manual activation (safer for multi-tenant production)
            revisionActivationPolicy: Automatic

            # Number of inactive revisions to keep
            # Useful for rollback scenarios
            revisionHistoryLimit: 3

            # Skip dependency resolution
            # Set to true if providers are pre-installed in the cluster
            skipDependencyResolution: true
          EOF
          
          echo "Generated catalog entry:"
          cat catalog-entry.yaml
      
      - name: Upload catalog entry as artifact
        uses: actions/upload-artifact@v4
        with:
          name: catalog-entry-${{ steps.version.outputs.VERSION }}
          path: catalog-entry.yaml
          retention-days: 30
      
      - name: Create GitHub Release
        if: github.event_name == 'push'
        uses: softprops/action-gh-release@v1
        with:
          name: Configuration DNS Record ${{ steps.version.outputs.VERSION }}
          body: |
            ## DNS Record Configuration Package ${{ steps.version.outputs.VERSION }}
            
            This release contains the Crossplane Configuration package for DNS record management.
            
            ### Installation
            
            Install directly using kubectl:
            ```bash
            kubectl apply -f - <<EOF
            apiVersion: pkg.crossplane.io/v1
            kind: Configuration
            metadata:
              name: configuration-dns-record
              namespace: crossplane-system
            spec:
              package: ${{ env.REGISTRY }}/${{ env.PACKAGE_NAME }}:${{ steps.version.outputs.VERSION }}
            EOF
            ```
            
            Or use the catalog entry from the artifacts.
            
            ### Package Details
            - Registry: `${{ env.REGISTRY }}/${{ env.PACKAGE_NAME }}`
            - Version: `${{ steps.version.outputs.VERSION }}`
            - Supports: Crossplane v2.0+
            - Includes: XRD + Composition for DNS records
            
            ### What's Included
            - Namespaced XRs for multi-tenant DNS management
            - Support for A, AAAA, CNAME, and TXT records
            - Mock provider for local development
            - Cloudflare provider for production
          files: |
            configuration-dns-record.xpkg
            catalog-entry.yaml
          draft: false
          prerelease: ${{ contains(steps.version.outputs.VERSION, '-') }}

      - name: Checkout Catalog Repository
        if: github.event_name == 'push'
        uses: actions/checkout@v4
        with:
          repository: open-service-portal/catalog
          token: ${{ secrets.GITHUB_TOKEN }}
          path: catalog

      # TODO: Create a custom action with necessary inputs and use it here
      - name: Update Catalog Entry
        if: github.event_name == 'push'
        run: |
          VERSION="${{ steps.version.outputs.VERSION }}"
          cp catalog-entry.yaml catalog/templates/template-dns-record.yaml
          cd catalog
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b update-dns-record-${VERSION}
          git add templates/template-dns-record.yaml
          git commit -m "chore: update DNS Record Configuration to ${VERSION}"
          git push origin update-dns-record-${VERSION}

      - name: Create Pull Request for Catalog Update
        if: github.event_name == 'push'
        run: |
          VERSION="${{ steps.version.outputs.VERSION }}"
          gh pr create \
            --repo open-service-portal/catalog \
            --title "Update DNS Record Configuration to ${VERSION}" \
            --body "This PR updates the DNS Record Configuration package reference in the catalog.
            
            **Version**: ${VERSION}
            **Package**: \`${{ env.REGISTRY }}/${{ env.PACKAGE_NAME }}:${VERSION}\`
            
            The catalog entry has been automatically generated from the release workflow." \
            --base main \
            --head update-dns-record-${VERSION}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
